# ranges:
#   Normal:
#     - {start: 0xF400, end: 0xF400, type: static, value: [0x00], 
#         supported_sessions: [0x01, 0x02, 0x03]}
#   TestResults:
#     - {start: 0xF600, end: 0xF600, type: static, value: [0x00], 
#         supported_sessions: [0x01, 0x02, 0x03]}
#   VehicleInformation:
#     - {start: 0xF800, end: 0xF800, type: static, value: [0x00], 
#         supported_sessoins: [0x01, 0x02, 0x03]}

# templates:
#   - category: DataStream
#     pattern: "Sensor_{index}"
#     start_id: 0xF700
#     count: 1
#     length: 4
#     type: function
#     func_name:
#     supported_sessions: [0x01, 0x02, 0x03]
#     supported_security_levels: all

specific:
  - id: 0x48F5
    name: "Variant Code"
    type: composite
    supported_services: [0x22, 0x2E]
    supported_sessions: [0x01, 0x02, 0x03]
    supported_security_levels: all
    supported_security_0x2E: [5, 10]
    supported_driving: all
    structure:
      - name: VC_Status
        type: dynamic
        source: read_VC_Status
        range: 0x00-0x00
      - name: VC_Code
        type: dynamic
        source: read_VC_Code
        range: 0x01-0x05
      - name: Reserved
        type: static
        value: [0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
          0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
          0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
          0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
          0x00, 0x00, 0x00]
        range: 0x06-0x37

  - id: 0x48AF
    name: "Variant Parts Number"
    type: composite
    supported_services: [0x22]
    supported_sessions: [0x01, 0x02, 0x03]
    supported_security_levels: all
    supported_driving: all
    structure:
      - name: VPN_Length
        type: dynamic
        source: read_VPN_Length
        range: 0x00-0x00
      - name: VPN_Id
        type: dynamic
        source: read_VPN_Id
        range: 0x01-0x0C
      - name: Reserved
        type: static
        value: [0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
          0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
          0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
          0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00]
        range: 0x0D-0x37

  - id: 0xA180
    name: "ECU ID"
    type: static
    value: [0x00, 0x26, 0x00, 0x00, 0x52, 0x00, 0x20, 0x00]
    length: 8
    supported_services: [0x22]
    supported_sessions: [0x01, 0x02, 0x03]
    supported_security_levels: all
    supported_driving: all

  - id: 0xA182
    name: "Current VehicleStatus"
    type: composite
    supported_sessions: [0x01, 0x02, 0x03]
    supported_services: [0x22]
    supported_security_levels: all
    supported_driving: all
    structure:
      - name: Reserve1
        type: static
        value: [0x00, 0x00]
        range: 0x00-0x01
      - name: SupportBits
        type: static
        value: [0x07, 0xFF, 0xF0, 0x02, 0x80, 0x00]
        range: 0x02-0x07
      - name: Reserve2
        type: static
        value: [0x00, 0x00, 0x00, 0x00, 0x00]
        range: 0x08-0x0C
      - name: METER_ODO_DATA
        type: dynamic
        source: read_METER_ODO_DATA
        range: 0x0D-0x0F
      - name: IG_ON_COUNTER
        type: dynamic
        source: read_IG_ON_COUNTER
        range: 0x10-0x12
      - name: IG_VOLTAGE
        type: dynamic
        source: read_IG_VOLTAGE
        range: 0x13-0x13
      - name: FL_WHEEL_SPEED
        type: dynamic
        source: read_FL_WHEEL_SPEED
        range: 0x14-0x14
      - name: FR_WHEEL_SPEED
        type: dynamic
        source: read_FR_WHEEL_SPEED
        range: 0x15-0x15
      - name: RL_WHEEL_SPEED
        type: dynamic
        source: read_RL_WHEEL_SPEED
        range: 0x16-0x16
      - name: RR_WHEEL_SPEED
        type: dynamic
        source: read_RR_WHEEL_SPEED
        range: 0x17-0x17
      - name: TM_SPEED
        type: dynamic
        source: read_TM_SPEED
        range: 0x18-0x18
      - name: LATERAL_G
        type: dynamic
        source: read_LATERAL_G
        range: 0x19-0x19
      - name: LONGITUDINAL_G
        type: dynamic
        source: read_LONGITUDINAL_G
        range: 0x1A-0x1A
      - name: YAW
        type: dynamic
        source: read_YAW
        range: 0x1B-0x1B
      - name: Reserve3
        type: static
        value: [0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
          0x00]
        range: 0x1C-0x27
      - name: STR_ANGLE
        type: dynamic
        source: read_STR_ANGLE
        range: 0x28-0x28
      - name: SHIFT_POS
        type: dynamic
        source: read_SHIFT_POS
        range: 0x29-0x29
      - name: Reserve4
        type: static
        value: [0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
          0x00, 0x00, 0x00]
        range: 0x2A-0x37

  - id: 0xA19D
    name: "Aiming date and time"
    type: static
    func_name: get_did_0xA19D
    supported_services: [0x22, 0x2E]
    supported_sessions: [0x03]
    supported_security_levels: all
    supported_driving: all
    length: 56

    value:
      - 1
      - 2
      - 3
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
    category: specific
  - id: 0xA192
    name: "Freeze Data of Vehicle Status"
    type: composite
    supported_services: [0x22]
    supported_sessions: [0x01, 0x02, 0x03]
    supported_security_levels: all
    supported_driving: all
    structure:
      - name: Reserve1
        type: static
        value: [0x00, 0x00]
        range: 0x00-0x01
      - name: SupportBits
        type: static
        value: [0xFF, 0xFF, 0xF0, 0x00, 0xC0, 0x00]
        range: 0x02-0x07
      - name: SCS_CODE
        type: dynamic
        source: read_SCS_CODE
        range: 0x08-0x08
      - name: SAE_CODE
        type: dynamic
        source: read_SAE_CODE
        range: 0x09-0x0B
      - name: DTC_STATUS
        type: dynamic
        source: read_DTC_STATUS
        range: 0x0C-0x0C
      - name: METER_ODO_DATA
        type: dynamic
        source: read_METER_ODO_DATA
        range: 0x0D-0x0F
      - name: IG_ON_COUNTER
        type: dynamic
        source: read_IG_ON_COUNTER
        range: 0x10-0x12
      - name: IG_VOLTAGE
        type: dynamic
        source: read_IG_VOLTAGE
        range: 0x13-0x13
      - name: FL_WHEEL_SPEED
        type: dynamic
        source: read_FL_WHEEL_SPEED
        range: 0x14-0x14
      - name: FR_WHEEL_SPEED
        type: dynamic
        source: read_FR_WHEEL_SPEED
        range: 0x15-0x15
      - name: RL_WHEEL_SPEED
        type: dynamic
        source: read_RL_WHEEL_SPEED
        range: 0x16-0x16
      - name: RR_WHEEL_SPEED
        type: dynamic
        source: read_RR_WHEEL_SPEED
        range: 0x17-0x17
      - name: TM_SPEED
        type: dynamic
        source: read_TM_SPEED
        range: 0x18-0x18
      - name: LATERAL_G
        type: dynamic
        source: read_LATERAL_G
        range: 0x19-0x19
      - name: LONGITUDINAL_G
        type: dynamic
        source: read_LONGITUDINAL_G
        range: 0x1A-0x1A
      - name: YAW
        type: dynamic
        source: read_YAW
        range: 0x1B-0x1B
      - name: Reserve3
        type: static
        value: [0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
          0x00]
        range: 0x1C-0x27
      - name: STR_ANGLE
        type: dynamic
        source: read_STR_ANGLE
        range: 0x28-0x28
      - name: SHIFT_POS
        type: dynamic
        source: read_SHIFT_POS
        range: 0x29-0x29
      - name: Reserve4
        type: static
        value: [0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
          0x00, 0x00, 0x00]
        range: 0x2A-0x37

  - id: 0xE602
    name: "Vehicle Conditions for Repro"
    type: static
    value: [0x00, 0x00, 0x00]
    length: 3
    supported_services: [0x22]
    supported_sessions: [0x01, 0x02, 0x03]
    supported_security_levels: all
    supported_driving: all

  - id: 0xD110
    name: "Signature Algorithm"
    type: function
    func_name: get_did_0xD110
    length: 6
    supported_services: [0x22]
    supported_sessions: [0x01, 0x02, 0x03]
    supported_security_levels: all
    supported_driving: all
